Provide a render missing method
This happened while running the specs

    NoMethodError:
        undefined method `render' for Haml::Filters::Markdown:Class

            Haml::Filters::Markdown.render markdown_source

The new haml update requires our filters to have a render method.